// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecruitmentAPI;

public partial class m_candidate
{
    public string Guid { get; set; }

    public int Id { get; set; }

    public string UserId { get; set; }

    public string CandidateName { get; set; }

    public DateTime BirthDate { get; set; }

    public string BirthPlace { get; set; }

    public string Gender { get; set; }

    public string Religion { get; set; }

    public virtual ICollection<m_candidate_profile> m_candidate_profile { get; set; } = new List<m_candidate_profile>();
}