// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecruitmentAPI;

public partial class m_candidate_profile_skill
{
    public string Guid { get; set; }

    public int Id { get; set; }

    public string ProfileId { get; set; }

    public string SkillName { get; set; }

    public string SkillDescription { get; set; }

    public virtual m_candidate_profile Profile { get; set; }
}