// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RecruitmentAPI;

public partial class m_candidate_profile
{
    public string Guid { get; set; }

    public int Id { get; set; }

    public string CandidateId { get; set; }

    public virtual m_candidate Candidate { get; set; }

    public virtual ICollection<m_candidate_profile_exp> m_candidate_profile_exp { get; set; } = new List<m_candidate_profile_exp>();

    public virtual ICollection<m_candidate_profile_skill> m_candidate_profile_skill { get; set; } = new List<m_candidate_profile_skill>();
}